# SPDX-FileCopyrightText: The openTCS Authors
# SPDX-License-Identifier: CC0-1.0

version = 1

[[annotations]]
path = ["**/*.gif", "**/*.jpg", "**/*.png", "**/*.svg"]
precedence = "closest"
SPDX-FileCopyrightText = "The openTCS Authors"
SPDX-License-Identifier = "CC-BY-4.0"
